AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam

  Sample SAM Template for sam

Parameters:
  Environment:
    Description: Enviroment Name
    Type: String
    Default: "dev"
  APIVersion:
    Description: API Version
    Type: String
    Default: "v1"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Environment:
      Variables:
        API_VERSION: !Ref APIVersion
  
Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sample_code/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Sample:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
      Layers:
        - !GetAtt AwsLambdaPowertoolsPythonLayer.Outputs.LayerVersionArn

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Sub ${Environment}
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
      RouteSettings:
        "ANY /{proxy+}":
          ThrottlingBurstLimit: 500 # overridden in HttpApi Event
  
  #
  # Application
  #

  AwsLambdaPowertoolsPythonLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer
        SemanticVersion: 1.29.2 # change to latest semantic version available in SAR
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete

